---
# Source: prometheus-operator/templates/exporters/core-dns/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: prometheus-prometheus-oper-coredns
  #Modified from upstream chart explicitly adding namespace
  namespace: design2
  labels:
    app: prometheus-operator-coredns
    jobLabel: coredns
    
    chart: prometheus-operator-4.3.2
    release: "prometheus"
    heritage: "Tiller"
    clusterName: ismail.oteemo-xc.com
    
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 9153
      protocol: TCP
      targetPort: 9153
  selector:
    
    k8s-app: coredns