---
# Source: prometheus-operator/charts/prometheus-node-exporter/templates/psp-clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:     
    app: prometheus-node-exporter
    heritage: Tiller
    release: prometheus
    chart: prometheus-node-exporter-1.3.0
    jobLabel: node-exporter
    
  name: psp-prometheus-prometheus-node-exporter
  #Modified from upstream chart explicitly adding namespace
  namespace: design2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-prometheus-prometheus-node-exporter
subjects:
  - kind: ServiceAccount
    name: prometheus-prometheus-node-exporter
    namespace: design2
