---
# Source: prometheus-operator/charts/grafana/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prometheus-grafana
  #Modified from upstream chart explicitly adding namespace
  namespace: design2
  labels:
    app: grafana
    chart: grafana-2.2.0
    heritage: Tiller
    release: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-grafana
subjects:
- kind: ServiceAccount
  name: prometheus-grafana
  namespace: design2