---
# Source: prometheus-operator/charts/grafana/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: grafana
    chart: grafana-2.2.0
    heritage: Tiller
    release: prometheus
  name: prometheus-grafana
  #Modified from upstream chart explicitly adding namespace
  namespace: design2
